### ISSUE TITLE
panic: runtime error: invalid memory address when sync with --filter-not-exist options

### ISSUE THREAD

**Issue by hoanhdo** [larrabee/s3sync#65]
Hi all.

I use s3sync to sync from local to s3 with command

./s3sync --tk xxx --ts yyyyyy --te "https://hn.ss.bfcplatform.vn" -w 8 /nfs/large/ s3://ffff-media/media/  --sync-progress --sync-log --filter-not-exist

I only want to sync file which not synced to s3

But it error 
```
INFO[0000] Starting sync                                
0 ListSource: Input: 0; Output: 4311 (31 obj/sec); Errors: 0
1 FilterObjectsExistNot: Input: 4310; Output: 0 (0 obj/sec); Errors: 0
2 LoadObjData: Input: 0; Output: 0 (0 obj/sec); Errors: 0
3 UploadObj: Input: 0; Output: 0 (0 obj/sec); Errors: 0
4 Logger: Input: 0; Output: 0 (0 obj/sec); Errors: 0
5 Terminator: Input: 0; Output: 0 (0 obj/sec); Errors: 0
Duration: 2m20.074378573s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x84f30b]

goroutine 35 [running]:
github.com/larrabee/s3sync/storage.StrongEtag(...)
        /home/larrabee/Work/opensource/s3sync/storage/utils.go:13
github.com/larrabee/s3sync/storage/s3.(*S3Storage).GetObjectMeta(0xc0003ba0e0, 0xc0044230e0)
        /home/larrabee/Work/opensource/s3sync/storage/s3/s3.go:262 +0x1cb
github.com/larrabee/s3sync/pipeline/collection.glob..func12(0xc000124a80, 0x0, 0x0, 0x0, 0x0)
        /home/larrabee/Work/opensource/s3sync/pipeline/collection/filter.go:201 +0xa8
github.com/larrabee/s3sync/pipeline.startWorkers.func1(0x1)
        /home/larrabee/Work/opensource/s3sync/pipeline/main.go:140 +0x90
created by github.com/larrabee/s3sync/pipeline.startWorkers
        /home/larrabee/Work/opensource/s3sync/pipeline/main.go:136 +0x33
```
How i can fix it.

Thanks.

**Comment by cl-bvl** [comment]
Hello.  
Thank you for report, fixed in new version.

**Comment by hoanhdo** [comment]
thanks
